#######################################################
#
#   Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#   By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#   By considering the terms in the Fibonacci sequence
#   whose values do not exceed four million, find the sum of the even-valued terms.
#######################################################

import sys

lijst = [1, 2]
som = 0

def generate(aantal):
    aantal = int(aantal)
    for i in range(2, aantal):
        lijst.append(lijst[i-1] + lijst[i-2])     
    return lijst

def check(lijst):
    cache = []
    for i in range(0, len(lijst)):
        if lijst[i] < 4000000 and lijst[i]%2 == 0:
            cache.append(lijst[i])
    lijst = cache
    return lijst

if __name__ == '__main__':
    aantal = sys.argv[1]
    lijst = generate(aantal)
    lijst = check(lijst)
    for i in range(0, len(lijst)):
        som += generate(aantal)[i]
        print generate(aantal)[i],
    print "\nDe som is: ",
    print som

